name: daily_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
    - family: Arial
      fonts:
        - asset: fonts/arial.ttf
    - family: Courier New
      fonts:
        - asset: fonts/cour.ttf
    - family: Times New Roman
      fonts:
        - asset: fonts/times.ttf
